<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Paynet FPX Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains the configuration for Paynet FPX payment integration.
    | Based on official Paynet documentation: https://docs.developer.paynet.my/docs/fpx/browser-redirection
    |
    */

    // Environment settings
    'environment' => env('PAYNET_ENVIRONMENT', 'uat'),
    
    // Environment-specific configurations
    'environments' => [
        'sit' => [
            'name' => 'SIT (System Integration Testing)',
            'api_url' => env('PAYNET_SIT_API_URL', 'https://sit.api.paynet.my'),
            'fpx_gateway_url' => env('PAYNET_SIT_GATEWAY_URL', 'https://sit.mepsfpx.com.my/FPXMain/seller2DReceiver.jsp'),
            'fpx_bank_list_url' => env('PAYNET_SIT_BANK_LIST_URL', 'https://sit.mepsfpx.com.my/FPXMain/RetrieveBankList'),
            'fpx_redirect_url' => env('PAYNET_SIT_REDIRECT_URL', 'https://sit.mepsfpx.com.my/FPXMain/processMesgFromSBIBanks.jsp'),
            'fpx_terms_url' => env('PAYNET_SIT_TERMS_URL', 'https://sit.mepsfpx.com.my/FPXMain/termsAndConditions.jsp'),
            'callback_url' => env('PAYNET_SIT_CALLBACK_URL', 'https://your-sit-domain.com/payment/paynet/callback'),
            'merchant_id' => env('PAYNET_SIT_MERCHANT_ID', 'EX00010946'),
            'merchant_name' => env('PAYNET_SIT_MERCHANT_NAME', 'Jariah Fund SIT'),
            'private_key_path' => env('PAYNET_SIT_PRIVATE_KEY_PATH', 'storage/keys/sit/merchant_private.key'),
            'public_cert_path' => env('PAYNET_SIT_PUBLIC_CERT_PATH', 'storage/keys/sit/paynet_public.cer'),
            'merchant_cert_path' => env('PAYNET_SIT_MERCHANT_CERT_PATH', 'storage/keys/sit/merchant_certificate.cer'),
            'timeout' => env('PAYNET_SIT_TIMEOUT', 30),
            'retry_attempts' => env('PAYNET_SIT_RETRY_ATTEMPTS', 3),
            'logging_level' => env('PAYNET_SIT_LOGGING_LEVEL', 'debug'),
        ],
        
        'uat' => [
            'name' => 'UAT (Testing)',
            'api_url' => env('PAYNET_UAT_API_URL', 'https://sandbox.api.paynet.my'),
            'fpx_gateway_url' => env('PAYNET_UAT_GATEWAY_URL', 'https://uat.mepsfpx.com.my/FPXMain/seller2DReceiver.jsp'),
            'fpx_bank_list_url' => env('PAYNET_UAT_BANK_LIST_URL', 'https://uat.mepsfpx.com.my/FPXMain/RetrieveBankList'),
            'fpx_redirect_url' => env('PAYNET_UAT_REDIRECT_URL', 'https://uat.mepsfpx.com.my/FPXMain/processMesgFromSBIBanks.jsp'),
            'fpx_terms_url' => env('PAYNET_UAT_TERMS_URL', 'https://uat.mepsfpx.com.my/FPXMain/termsAndConditions.jsp'),
            'callback_url' => env('PAYNET_UAT_CALLBACK_URL', 'https://your-uat-domain.com/payment/paynet/callback'),
            'merchant_id' => env('PAYNET_UAT_MERCHANT_ID', 'EX00010946'),
            'merchant_name' => env('PAYNET_UAT_MERCHANT_NAME', 'Jariah Fund UAT'),
            'private_key_path' => env('PAYNET_UAT_PRIVATE_KEY_PATH', 'storage/keys/uat/merchant_private.key'),
            'public_cert_path' => env('PAYNET_UAT_PUBLIC_CERT_PATH', 'storage/keys/uat/paynet_public.cer'),
            'merchant_cert_path' => env('PAYNET_UAT_MERCHANT_CERT_PATH', 'storage/keys/uat/merchant_certificate.cer'),
            'timeout' => env('PAYNET_UAT_TIMEOUT', 30),
            'retry_attempts' => env('PAYNET_UAT_RETRY_ATTEMPTS', 3),
            'logging_level' => env('PAYNET_UAT_LOGGING_LEVEL', 'debug'),
        ],
        
        'prod' => [
            'name' => 'Production',
            'api_url' => env('PAYNET_PROD_API_URL', 'https://api.paynet.my'),
            'fpx_gateway_url' => env('PAYNET_PROD_GATEWAY_URL', 'https://www.mepsfpx.com.my/FPXMain/seller2DReceiver.jsp'),
            'fpx_bank_list_url' => env('PAYNET_PROD_BANK_LIST_URL', 'https://www.mepsfpx.com.my/FPXMain/RetrieveBankList'),
            'fpx_redirect_url' => env('PAYNET_PROD_REDIRECT_URL', 'https://www.mepsfpx.com.my/FPXMain/processMesgFromSBIBanks.jsp'),
            'fpx_terms_url' => env('PAYNET_PROD_TERMS_URL', 'https://www.mepsfpx.com.my/FPXMain/termsAndConditions.jsp'),
            'callback_url' => env('PAYNET_PROD_CALLBACK_URL', 'https://your-domain.com/payment/paynet/callback'),
            'merchant_id' => env('PAYNET_PROD_MERCHANT_ID', 'EX00010946'),
            'merchant_name' => env('PAYNET_PROD_MERCHANT_NAME', 'Jariah Fund'),
            'private_key_path' => env('PAYNET_PROD_PRIVATE_KEY_PATH', 'storage/keys/prod/merchant_private.key'),
            'public_cert_path' => env('PAYNET_PROD_PUBLIC_CERT_PATH', 'storage/keys/prod/paynet_public.cer'),
            'merchant_cert_path' => env('PAYNET_PROD_MERCHANT_CERT_PATH', 'storage/keys/prod/merchant_certificate.cer'),
            'timeout' => env('PAYNET_PROD_TIMEOUT', 60),
            'retry_attempts' => env('PAYNET_PROD_RETRY_ATTEMPTS', 5),
            'logging_level' => env('PAYNET_PROD_LOGGING_LEVEL', 'info'),
        ],
        
        'production' => [
            'name' => 'Production',
            'api_url' => env('PAYNET_PROD_API_URL', 'https://api.paynet.my'),
            'fpx_gateway_url' => env('PAYNET_PROD_GATEWAY_URL', 'https://www.mepsfpx.com.my/FPXMain/seller2DReceiver.jsp'),
            'fpx_bank_list_url' => env('PAYNET_PROD_BANK_LIST_URL', 'https://www.mepsfpx.com.my/FPXMain/RetrieveBankList'),
            'fpx_redirect_url' => env('PAYNET_PROD_REDIRECT_URL', 'https://www.mepsfpx.com.my/FPXMain/processMesgFromSBIBanks.jsp'),
            'fpx_terms_url' => env('PAYNET_PROD_TERMS_URL', 'https://www.mepsfpx.com.my/FPXMain/termsAndConditions.jsp'),
            'callback_url' => env('PAYNET_PROD_CALLBACK_URL', 'https://your-domain.com/payment/paynet/callback'),
            'merchant_id' => env('PAYNET_PROD_MERCHANT_ID', 'EX00010946'),
            'merchant_name' => env('PAYNET_PROD_MERCHANT_NAME', 'Jariah Fund'),
            'private_key_path' => env('PAYNET_PROD_PRIVATE_KEY_PATH', 'storage/keys/prod/merchant_private.key'),
            'public_cert_path' => env('PAYNET_PROD_PUBLIC_CERT_PATH', 'storage/keys/prod/paynet_public.cer'),
            'merchant_cert_path' => env('PAYNET_PROD_MERCHANT_CERT_PATH', 'storage/keys/prod/merchant_certificate.cer'),
            'timeout' => env('PAYNET_PROD_TIMEOUT', 60),
            'retry_attempts' => env('PAYNET_PROD_RETRY_ATTEMPTS', 5),
            'logging_level' => env('PAYNET_PROD_LOGGING_LEVEL', 'info'),
        ],
        
        'development' => [
            'name' => 'Development',
            'api_url' => env('PAYNET_DEV_API_URL', 'https://sandbox.api.paynet.my'),
            'fpx_gateway_url' => env('PAYNET_DEV_GATEWAY_URL', 'https://uat.mepsfpx.com.my/FPXMain/seller2DReceiver.jsp'),
            'fpx_bank_list_url' => env('PAYNET_DEV_BANK_LIST_URL', 'https://uat.mepsfpx.com.my/FPXMain/RetrieveBankList'),
            'fpx_redirect_url' => env('PAYNET_DEV_REDIRECT_URL', 'https://uat.mepsfpx.com.my/FPXMain/processMesgFromSBIBanks.jsp'),
            'fpx_terms_url' => env('PAYNET_DEV_TERMS_URL', 'https://uat.mepsfpx.com.my/FPXMain/termsAndConditions.jsp'),
            'callback_url' => env('PAYNET_DEV_CALLBACK_URL', 'http://localhost:8000/payment/paynet/callback'),
            'merchant_id' => env('PAYNET_DEV_MERCHANT_ID', 'EX00010946'),
            'merchant_name' => env('PAYNET_DEV_MERCHANT_NAME', 'Jariah Fund Dev'),
            'private_key_path' => env('PAYNET_DEV_PRIVATE_KEY_PATH', 'storage/keys/dev/merchant_private.key'),
            'public_cert_path' => env('PAYNET_DEV_PUBLIC_CERT_PATH', 'storage/keys/dev/paynet_public.cer'),
            'merchant_cert_path' => env('PAYNET_DEV_MERCHANT_CERT_PATH', 'storage/keys/dev/merchant_certificate.cer'),
            'timeout' => env('PAYNET_DEV_TIMEOUT', 30),
            'retry_attempts' => env('PAYNET_DEV_RETRY_ATTEMPTS', 2),
            'logging_level' => env('PAYNET_DEV_LOGGING_LEVEL', 'debug'),
        ],
    ],
    
    // FPX settings
    'fpx_version' => '7.0',
    'fpx_msg_token' => '01',
    'fpx_msg_type' => 'AR', // Authorization Request for payment initiation
    
    // Transaction limits (in MYR)
    'min_amount' => env('PAYNET_MIN_AMOUNT', 1.00),
    'max_amount' => env('PAYNET_MAX_AMOUNT', 50000.00),
    
    // Response codes mapping
    'response_codes' => [
        '00' => 'Successful',
        '09' => 'Pending',
        '99' => 'Pending for Authorization',
        '01' => 'Invalid Merchant',
        '02' => 'Invalid Bank',
        '03' => 'Invalid Amount',
        '04' => 'Invalid Currency',
        '05' => 'Invalid Transaction',
        '06' => 'Invalid Response',
        '07' => 'Invalid Signature',
        '08' => 'Invalid Message',
        '10' => 'Bank Offline',
        '11' => 'Bank Timeout',
        '12' => 'Bank Error',
        '13' => 'Bank Rejected',
        '14' => 'Bank Cancelled',
        '15' => 'Bank Declined',
        '16' => 'Bank Expired',
        '17' => 'Bank Invalid',
        '18' => 'Bank Unavailable',
        '19' => 'Bank Busy',
        '20' => 'Bank Maintenance',
        '21' => 'Bank Suspended',
        '22' => 'Bank Blocked',
        '23' => 'Bank Disabled',
        '24' => 'Bank Inactive',
        '25' => 'Bank Deleted',
        '26' => 'Bank Not Found',
        '27' => 'Bank Not Authorized',
        '28' => 'Bank Not Supported',
        '29' => 'Bank Not Available',
        '30' => 'Bank Not Responding',
        '31' => 'Bank Not Connected',
        '32' => 'Bank Not Reachable',
        '33' => 'Bank Not Accessible',
        '34' => 'Bank Not Operational',
        '35' => 'Bank Not Functional',
        '36' => 'Bank Not Working',
        '37' => 'Bank Not Active',
        '38' => 'Bank Not Ready',
        '39' => 'Bank Not Configured',
        '40' => 'Bank Not Initialized',
        '41' => 'Bank Not Started',
        '42' => 'Bank Not Running',
        '43' => 'Bank Not Online',
        '44' => 'Bank Not Available',
        '45' => 'Bank Not Responding',
        '46' => 'Bank Not Connected',
        '47' => 'Bank Not Reachable',
        '48' => 'Bank Not Accessible',
        '49' => 'Bank Not Operational',
        '50' => 'Bank Not Functional',
        '51' => 'Bank Not Working',
        '52' => 'Bank Not Active',
        '53' => 'Bank Not Ready',
        '54' => 'Bank Not Configured',
        '55' => 'Bank Not Initialized',
        '56' => 'Bank Not Started',
        '57' => 'Bank Not Running',
        '58' => 'Bank Not Online',
        '59' => 'Bank Not Available',
        '60' => 'Bank Not Responding',
        '61' => 'Bank Not Connected',
        '62' => 'Bank Not Reachable',
        '63' => 'Bank Not Accessible',
        '64' => 'Bank Not Operational',
        '65' => 'Bank Not Functional',
        '66' => 'Bank Not Working',
        '67' => 'Bank Not Active',
    ],
    
    // User-friendly error messages
    'user_messages' => [
        '00' => 'Payment completed successfully',
        '09' => 'Payment is being processed. Please check your bank account for confirmation.',
        '99' => 'Payment is pending authorization from your bank. Please check your bank account.',
        '01' => 'Payment failed: Invalid merchant configuration',
        '02' => 'Payment failed: Invalid bank selection',
        '03' => 'Payment failed: Invalid amount',
        '04' => 'Payment failed: Invalid currency',
        '05' => 'Payment failed: Invalid transaction',
        '06' => 'Payment failed: Invalid response from bank',
        '07' => 'Payment failed: Security verification failed',
        '08' => 'Payment failed: Invalid message format',
        '10' => 'Payment failed: Bank is currently offline',
        '11' => 'Payment failed: Bank timeout. Please try again.',
        '12' => 'Payment failed: Bank error occurred',
        '13' => 'Payment failed: Bank rejected the transaction',
        '14' => 'Payment cancelled by user',
        '15' => 'Payment failed: Bank declined the transaction',
        '16' => 'Payment failed: Transaction expired',
        '17' => 'Payment failed: Invalid bank details',
        '18' => 'Payment failed: Bank service unavailable',
        '19' => 'Payment failed: Bank is busy. Please try again.',
        '20' => 'Payment failed: Bank is under maintenance',
        '21' => 'Payment failed: Bank service suspended',
        '22' => 'Payment failed: Bank account blocked',
        '23' => 'Payment failed: Bank service disabled',
        '24' => 'Payment failed: Bank account inactive',
        '25' => 'Payment failed: Bank account deleted',
        '26' => 'Payment failed: Bank not found',
        '27' => 'Payment failed: Bank not authorized',
        '28' => 'Payment failed: Bank not supported',
        '29' => 'Payment failed: Bank not available',
        '30' => 'Payment failed: Bank not responding',
        '31' => 'Payment failed: Bank not connected',
        '32' => 'Payment failed: Bank not reachable',
        '33' => 'Payment failed: Bank not accessible',
        '34' => 'Payment failed: Bank not operational',
        '35' => 'Payment failed: Bank not functional',
        '36' => 'Payment failed: Bank not working',
        '37' => 'Payment failed: Bank not active',
        '38' => 'Payment failed: Bank not ready',
        '39' => 'Payment failed: Bank not configured',
        '40' => 'Payment failed: Bank not initialized',
        '41' => 'Payment failed: Bank not started',
        '42' => 'Payment failed: Bank not running',
        '43' => 'Payment failed: Bank not online',
        '44' => 'Payment failed: Bank not available',
        '45' => 'Payment failed: Bank not responding',
        '46' => 'Payment failed: Bank not connected',
        '47' => 'Payment failed: Bank not reachable',
        '48' => 'Payment failed: Bank not accessible',
        '49' => 'Payment failed: Bank not operational',
        '50' => 'Payment failed: Bank not functional',
        '51' => 'Payment failed: Bank not working',
        '52' => 'Payment failed: Bank not active',
        '53' => 'Payment failed: Bank not ready',
        '54' => 'Payment failed: Bank not configured',
        '55' => 'Payment failed: Bank not initialized',
        '56' => 'Payment failed: Bank not started',
        '57' => 'Payment failed: Bank not running',
        '58' => 'Payment failed: Bank not online',
        '59' => 'Payment failed: Bank not available',
        '60' => 'Payment failed: Bank not responding',
        '61' => 'Payment failed: Bank not connected',
        '62' => 'Payment failed: Bank not reachable',
        '63' => 'Payment failed: Bank not accessible',
        '64' => 'Payment failed: Bank not operational',
        '65' => 'Payment failed: Bank not functional',
        '66' => 'Payment failed: Bank not working',
        '67' => 'Payment failed: Bank not active',
    ],
    
    // Default settings
    'defaults' => [
        'currency' => 'MYR',
        'language' => 'en',
        'timeout' => 30,
        'retry_attempts' => 3,
    ],
    
    // Logging settings
    'logging' => [
        'enabled' => env('PAYNET_LOGGING_ENABLED', true),
        'level' => env('PAYNET_LOGGING_LEVEL', 'info'),
        'channel' => env('PAYNET_LOGGING_CHANNEL', 'paynet'),
    ],
]; 